// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp22v6Xj_b5HejqPpy8jJUIXLXcghjXM0',
    appId: '1:713607552371:web:0d3ed675d57f4972f17906',
    messagingSenderId: '713607552371',
    projectId: 'fir-flutter-codelab-d7703',
    authDomain: 'fir-flutter-codelab-d7703.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-d7703.appspot.com',
    measurementId: 'G-SL78VW01L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2N4OFEBO-En7z2YlqzqxUYsq7tEe87Ss',
    appId: '1:713607552371:android:c2a14c3a9ca01c84f17906',
    messagingSenderId: '713607552371',
    projectId: 'fir-flutter-codelab-d7703',
    storageBucket: 'fir-flutter-codelab-d7703.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCS_kGw5bCH2whTyCouX8elmviXbcNlZRM',
    appId: '1:713607552371:ios:48d5e81be8875a49f17906',
    messagingSenderId: '713607552371',
    projectId: 'fir-flutter-codelab-d7703',
    storageBucket: 'fir-flutter-codelab-d7703.appspot.com',
    iosClientId: '713607552371-srgpl0bgn860uk7hv1ujfmbmkuoi6ph0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCS_kGw5bCH2whTyCouX8elmviXbcNlZRM',
    appId: '1:713607552371:ios:48d5e81be8875a49f17906',
    messagingSenderId: '713607552371',
    projectId: 'fir-flutter-codelab-d7703',
    storageBucket: 'fir-flutter-codelab-d7703.appspot.com',
    iosClientId: '713607552371-srgpl0bgn860uk7hv1ujfmbmkuoi6ph0.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
